#!/usr/bin/env node
// ============================================================
// AXIOM — Environment injection (build step)
// ------------------------------------------------------------
// Reads SUPABASE_URL / SUPABASE_ANON_KEY from process.env and
// writes js/core/env.config.js from the checked-in template,
// substituting the real values. Run this as the build command
// (see package.json → "build") on Vercel (or any host) before
// the static files are served — never commit the generated file.
//
// This is the only place a real Supabase credential ever touches
// disk in this project, and it's written from an environment
// variable, not typed into source. js/core/env.config.js is listed
// in .gitignore.
//
// Exit codes:
//   0 — env.config.js written successfully
//   1 — a required environment variable is missing/empty
// ============================================================
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const TEMPLATE_PATH = path.join(ROOT, 'js', 'core', 'env.config.template.js');
const OUTPUT_PATH = path.join(ROOT, 'js', 'core', 'env.config.js');

const REQUIRED_VARS = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];

function fail(message) {
  console.error(`[inject-env] ERROR: ${message}`);
  process.exit(1);
}

function main() {
  const missing = REQUIRED_VARS.filter((name) => !process.env[name] || !String(process.env[name]).trim());
  if (missing.length) {
    fail(
      `Missing required environment variable(s): ${missing.join(', ')}. ` +
      `Set them in your host's environment settings (e.g. Vercel Project ` +
      `Settings → Environment Variables) before running the build.`
    );
    return;
  }

  if (!fs.existsSync(TEMPLATE_PATH)) {
    fail(`Template not found at ${TEMPLATE_PATH}`);
    return;
  }

  let contents = fs.readFileSync(TEMPLATE_PATH, 'utf8');

  // Strip the template's own explanatory header comment block from the
  // generated output so the real config file stays short — the template
  // remains the source of truth for documentation.
  contents = contents.replace(/^\/\/ =+[\s\S]*?\/\/ =+\n/, '');

  contents = contents
    .replace('__SUPABASE_URL__', String(process.env.SUPABASE_URL).trim())
    .replace('__SUPABASE_ANON_KEY__', String(process.env.SUPABASE_ANON_KEY).trim());

  const banner =
    '// AUTO-GENERATED by scripts/inject-env.js at build time. Do not edit\n' +
    '// by hand and do not commit — see js/core/env.config.template.js.\n';

  fs.writeFileSync(OUTPUT_PATH, banner + contents, 'utf8');
  console.log(`[inject-env] Wrote ${path.relative(ROOT, OUTPUT_PATH)}`);
}

main();
